context:
  name: pixi-diff
  version: "0.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/pavelzw/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: f93b41ae75bfcc4001840a3d10ade082a1b4fa8e58437e6610c071ad7292c223

build:
  number: 0
  # https://github.com/conda-forge/staged-recipes/pull/28929#issuecomment-2613880733
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses

tests:
  - script:
      - pixi-diff --version

about:
  homepage: https://github.com/pavelzw/pixi-diff
  summary: Generate JSON diffs between pixi lockfiles
  description: |
    A simple executable to generate a JSON diff (similar to `pixi update --json`) between two pixi lockfiles.
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/pavelzw/pixi-diff

extra:
  recipe-maintainers:
    - pavelzw
