context:
  name: pixi-diff
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/pavelzw/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 01b8b97776da8d7851bbee5f55d26c89b4befd2ba67b1c3a7582a831c1f5042f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses

tests:
  - script:
      - pixi-diff --version

about:
  homepage: https://github.com/pavelzw/pixi-diff
  summary: Generate JSON diffs between pixi lockfiles
  description: |
    A simple executable to generate a JSON diff (similar to `pixi update --json`) between two pixi lockfiles.
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/pavelzw/pixi-diff

extra:
  recipe-maintainers:
    - pavelzw
